package net.vaultmc.vaultcore;

import net.vaultmc.vaultcore.commands.*;
import net.vaultmc.vaultcore.commands.economy.EconomyCommand;
import net.vaultmc.vaultcore.commands.economy.MoneyCommand;
import net.vaultmc.vaultcore.commands.economy.TransferCommand;
import net.vaultmc.vaultcore.commands.msg.MsgCommand;
import net.vaultmc.vaultcore.commands.msg.ReplyCommand;
import net.vaultmc.vaultcore.commands.msg.SocialSpyCommand;
import net.vaultmc.vaultcore.commands.report.ReportCommand;
import net.vaultmc.vaultcore.commands.report.ReportsCommand;
import net.vaultmc.vaultcore.commands.settings.SettingsCommand;
import net.vaultmc.vaultcore.commands.settings.SettingsListener;
import net.vaultmc.vaultcore.commands.staff.*;
import net.vaultmc.vaultcore.commands.staff.gamemode.GMCreativeCommand;
import net.vaultmc.vaultcore.commands.staff.gamemode.GMSpectatorCommand;
import net.vaultmc.vaultcore.commands.staff.gamemode.GMSurvivalCommand;
import net.vaultmc.vaultcore.commands.staff.gamemode.GameModeCommand;
import net.vaultmc.vaultcore.commands.staff.grant.GrantCommand;
import net.vaultmc.vaultcore.commands.staff.grant.GrantCommandListener;
import net.vaultmc.vaultcore.commands.staff.punishments.ban.*;
import net.vaultmc.vaultcore.commands.staff.punishments.kick.KickCommand;
import net.vaultmc.vaultcore.commands.staff.punishments.mute.*;
import net.vaultmc.vaultcore.commands.teleport.*;
import net.vaultmc.vaultcore.commands.worldtp.CRCommand;
import net.vaultmc.vaultcore.commands.worldtp.SVCommand;
import net.vaultmc.vaultcore.listeners.*;
import net.vaultmc.vaultcore.listeners.inventory.InventoryStorageListeners;
import net.vaultmc.vaultcore.survival.SleepHandler;

public class Registry {
	private static final VaultCore vault = VaultCore.getInstance();

	public static void registerCommands() {
		new MsgCommand();
		new ReplyCommand();
		new SettingsCommand();
		new TPACommand();
		new TPAcceptCommand();
		new TPAHereCommand();
		new TPHereCommand();
		new TPDenyCommand();
		new WarpCommand();
		new CRCommand();
		new SVCommand();
		new BackCommand();
		new DiscordCommand();
		new PingCommand();
		new PlayTimeCommand();
		new RanksCommand();
		new SeenCommand();
		new TokenCommand();
		new WildTeleportCommand();
		new GrantCommand();
		new GameModeCommand();
		new GMCreativeCommand();
		new GMSurvivalCommand();
		new GMSpectatorCommand();
		new CheckCommand();
		new ClearChatCommand();
		new ConsoleSay();
		new FeedCommand();
		new FlyCommand();
		new HealCommand();
		new InvseeCommand();
		new MuteChatCommand();
		new StaffChatCommand();
		new TPCommand();
		new ReloadCommand();
		new HasPermCommand();
		new TagCommand();
		new StatsCommand();
		new ListCommand();
		new SocialSpyCommand();
        new ModMode();
        new ReportCommand();
        new ReportsCommand();
        new AFKCommand();
        new ChatUtils();
        new EconomyCommand();
        new MoneyCommand();
        new TimeCommand();
        new TransferCommand();
        new VanishCommand();
        new VanishListeners();
        new InventoryStorageListeners();
        new GameModeListeners();
        new WeatherCommand();
        new HelpCommand();
        new BrandCommand();
        new KickCommand();
        new BanCommand();
        new MuteCommand();
        new UnbanCommand();
        new IpBanCommand();
        new IpTempBanCommand();
        new IpMuteCommand();
        new IpTempMuteCommand();
        new UnmuteCommand();
        new TempBanCommand();
        new TempMuteCommand();
	}

	public static void registerListeners() {
		vault.registerEvents(new GrantCommandListener());
		vault.registerEvents(new SignColours());
		vault.registerEvents(new PlayerJoinQuitListener());
		vault.registerEvents(new PlayerTPListener());
		vault.registerEvents(new SettingsListener());
		vault.registerEvents(new CycleListener());
		vault.registerEvents(new ShutDownListener());
        vault.registerEvents(new BannedListener());
        vault.registerEvents(new MutedListener());
        vault.registerEvents(new SleepHandler());
	}
}